### PR TITLE
Calculate correct indentation of rST comments.

### LINKED ISSUE #43: Problems with indenting comments in ``rst`` document
Just to make a note here about issue https://github.com/vim/vim/issues/5142.

### PR DESCRIPTION
**Pull request by mcepl**
I would find that this should work, but I don’t see any change with regards to behaviour about comments in rST.

Fixes #43

### CODE REVIEW

**Comment by mcepl** [comment]
OK, I found out I have wrong value of ``rtp``, but when it is fixed, this fix seems to work just fine.

**Comment by marshallward** [comment]
This seems to work for me as well.  Thanks very much for resolving this, I don't think I would have found the time to handle it.

**Comment by marshallward** [comment]
BTW if there's any issues we can handle them in other issues.  The great thing is that you've managed to bootstrap the process.

**Comment by mcepl** [comment]
I haven’t checked, but how far is this fork from the canonical vim? Do you plan to submit this repo to Bram?

**Comment by marshallward** [comment]
It's a bit out of date, I ought to do it soon.  There was an outstanding issue that I wanted to sort out, but it may have to wait since I don't know when we will get it done.  I'll send something by the end of week though.

**Comment by mcepl** [comment]
> There was an outstanding issue that I wanted to sort out, but it may have to wait since I don't know when we will get it done.

Which one? I may get some time to take a look.

**Comment by marshallward** [comment]
Mainly just #44 since I have to decide if the proposed solution is needed, or if it can be done with a simple regexp change.

**Comment by mcepl** [comment]
OK, no clue about syntax files. Sorry.

**Pull request merged**
